server:
  port: 8003
spring:
  application:
    name: springcloud-provider-8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-zuul-8003

#配置监控信息
info:
  app.name: enjieTest


#配置zuul
zuul:
  routes:
    mydept.serviceId: SPRINGCLOUD-PROVIDER-8001
    mydept.path: /mydept/**
