server:
  port: 8001
mybatis:
  type-aliases-package: com.enjie.bean
  mapper-locations: classpath:mapper/*.xml
spring:
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-8001

#配置监控信息
info:
  app.name: enjieTest
logging:
  level:
    com.enjie.mapper : debug